#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Matlab on August 08, 2024 at 17:01:29.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[25];
extern c_float ldata[37];
extern c_float udata[37];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[25];
extern c_float Dinvscaling[25];
extern c_float Escaling[37];
extern c_float Einvscaling[37];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[62];
extern c_int linsys_solver_P[62];
extern c_float linsys_solver_bp[62];
extern c_float linsys_solver_sol[62];
extern c_float linsys_solver_rho_inv_vec[37];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[25];
extern c_float ysolution[37];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[37];
extern c_float work_rho_inv_vec[37];
extern c_float work_x[25];
extern c_float work_y[37];
extern c_float work_z[37];
extern c_float work_xz_tilde[62];
extern c_float work_x_prev[25];
extern c_float work_z_prev[37];
extern c_float work_Ax[37];
extern c_float work_Px[25];
extern c_float work_Aty[25];
extern c_float work_delta_y[37];
extern c_float work_Atdelta_y[25];
extern c_float work_delta_x[25];
extern c_float work_Pdelta_x[25];
extern c_float work_Adelta_x[37];
extern c_float work_D_temp[25];
extern c_float work_D_temp_A[25];
extern c_float work_E_temp[37];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
